version: '3'
services:
  web:
    build: .
    ports:
      - "7860:7860"
    environment:
      - SPARK_APPID=${SPARK_APPID}
      - SPARK_API_SECRET=${SPARK_API_SECRET}
      - SPARK_API_KEY=${SPARK_API_KEY}
    volumes:
      - ./app:/app/app